import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";


export const metadata: Metadata = {
  title: "Fullstack Next.js",
  description: "Generated by Fullstack Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
       <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
